/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek.saranaPrasarana;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;

/**
 *
 * @author AlCaMiC
 */
public class PengembalianBarang extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private DefaultTableModel model;
    public PengembalianBarang() {
        initComponents();
        scaleImage();
        scaleImage1();
        loadBarang();
        ComboBarang.addItemListener(new java.awt.event.ItemListener() {
        @Override
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                onComboBarangSelection(evt);
            }
        }
    });

        
    }
    public void loadBarang(){
        try {
        Connection c = KoneksiDatabase.getKoneksi();
        Statement s = c.createStatement();

        // Query untuk mendapatkan nama_peminjam dan nama_barang
        String sql = "SELECT nama_peminjam, nama_barang, jumlah_pinjam FROM pinjambarang WHERE tanggal_kembali IS NULL;";
        ResultSet r = s.executeQuery(sql);

        // Kosongkan ComboBox sebelum memuat data baru
        ComboBarang.removeAllItems();

        while (r.next()) {
            // Gabungkan nama_peminjam dan nama_barang
            String namaPeminjam = r.getString("nama_peminjam");
            String namaBarang = r.getString("nama_barang");
            int jumlahPinjam = r.getInt("jumlah_pinjam");
            String combinedItem = namaPeminjam + " - " + namaBarang + " - " + jumlahPinjam;

            // Tambahkan ke ComboBarang
            ComboBarang.addItem(combinedItem);
        }

        r.close();
        s.close();
    } catch (Exception e) {
        e.printStackTrace();
        System.out.println("Terjadi kesalahan saat memuat data ke ComboBarang.");
    }
    }
    
    private void scaleImage(){
        ImageIcon icon = new ImageIcon("D:\\Projek Lanjut\\logo1.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(icon1.getWidth(), icon1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        icon1.setIcon(scaledIcon);

    }
    private void scaleImage1(){
        ImageIcon icon = new ImageIcon("D:\\Projek Lanjut\\logo2.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(icon2.getWidth(), icon2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        icon2.setIcon(scaledIcon);

    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        icon1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        beranda = new javax.swing.JButton();
        barang = new javax.swing.JButton();
        Kelas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        ComboBarang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        kembaliBarang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(58, 130, 255));

        icon1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sarana Prasarana JTIK");

        beranda.setBackground(new java.awt.Color(58, 130, 255));
        beranda.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 255));
        beranda.setText("Beranda");
        beranda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berandaActionPerformed(evt);
            }
        });

        barang.setBackground(new java.awt.Color(58, 130, 255));
        barang.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        barang.setForeground(new java.awt.Color(255, 255, 255));
        barang.setText("Barang");
        barang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        barang.setMaximumSize(new java.awt.Dimension(63, 36));
        barang.setMinimumSize(new java.awt.Dimension(63, 36));
        barang.setPreferredSize(new java.awt.Dimension(63, 36));
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });

        Kelas.setBackground(new java.awt.Color(58, 130, 255));
        Kelas.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        Kelas.setForeground(new java.awt.Color(255, 255, 255));
        Kelas.setText("Kelas");
        Kelas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 672, Short.MAX_VALUE)
                .addComponent(beranda, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(barang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beranda)
                    .addComponent(barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(58, 130, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pengembalian Barang");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 48));

        icon2.setText("jLabel1");
        jPanel4.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 64));

        ComboBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBarangItemStateChanged(evt);
            }
        });
        ComboBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBarangActionPerformed(evt);
            }
        });
        jPanel4.add(ComboBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 310, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pilih Nama Peminjam");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        kembaliBarang.setText("Kembali Barang");
        kembaliBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBarangActionPerformed(evt);
            }
        });
        jPanel4.add(kembaliBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 520, 330));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(927, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 84, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void berandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaActionPerformed
        // TODO add your handling code here:
         new Beranda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_berandaActionPerformed

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
        // TODO add your handling code here:
        new DaftarBarang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_barangActionPerformed

    private void refreshComboBox() {
    ComboBarang.removeAllItems(); // Clear existing items
    loadBarang(); // Reload the available classes
}
    
    private void kembaliBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBarangActionPerformed
   // Retrieve data from input fields
     String selectedItem = (String) ComboBarang.getSelectedItem();

    if (selectedItem == null || selectedItem.isEmpty()) {
        System.out.println("Pilih barang yang ingin dikembalikan.");
        return;
    }

    // Pisahkan `nama_peminjam` dan `nama_barang`
    String[] parts = selectedItem.split(" - ");
    if (parts.length < 2) {
        System.out.println("Format data ComboBox tidak valid.");
        return;
    }

    String namaPeminjam = parts[0].trim();
    String namaBarang = parts[1].trim();

    try {
        Connection c = KoneksiDatabase.getKoneksi();

        // Step 1: Ambil jumlah pinjam dari tabel `pinjambarang`
        String fetchQuery = "SELECT jumlah_pinjam FROM pinjambarang WHERE nama_peminjam = ? AND nama_barang = ? AND tanggal_kembali IS NULL;";
        PreparedStatement fetchStmt = c.prepareStatement(fetchQuery);
        fetchStmt.setString(1, namaPeminjam);
        fetchStmt.setString(2, namaBarang);
        ResultSet rs = fetchStmt.executeQuery();

        int jumlahPinjam = 0;

        if (rs.next()) {
            jumlahPinjam = rs.getInt("jumlah_pinjam");
        } else {
            System.out.println("Data peminjaman tidak ditemukan.");
            return;
        }

        rs.close();
        fetchStmt.close();

        // Step 2: Perbarui tabel `databarang` untuk mengembalikan stok
        String updateStockQuery = "UPDATE databarang SET jumlah_total = jumlah_total + ?, jumlah_baik = jumlah_baik + ?, jumlah_kurang_baik = jumlah_kurang_baik WHERE nama_barang = ?;";
        PreparedStatement updateStockStmt = c.prepareStatement(updateStockQuery);
        updateStockStmt.setInt(1, jumlahPinjam);
        updateStockStmt.setInt(2, jumlahPinjam); // Diasumsikan semua barang kembali dalam kondisi baik
        updateStockStmt.setString(3, namaBarang);
        updateStockStmt.executeUpdate();
        updateStockStmt.close();

        // Step 3: Perbarui tanggal kembali di tabel `pinjambarang`
        String updateReturnDateQuery = "UPDATE pinjambarang SET tanggal_kembali = CURRENT_DATE WHERE nama_peminjam = ? AND nama_barang = ? AND tanggal_kembali IS NULL;";
        PreparedStatement updateReturnDateStmt = c.prepareStatement(updateReturnDateQuery);
        updateReturnDateStmt.setString(1, namaPeminjam);
        updateReturnDateStmt.setString(2, namaBarang);
        updateReturnDateStmt.executeUpdate();
        updateReturnDateStmt.close();

        System.out.println("Barang berhasil dikembalikan!");
    } catch (SQLException e) {
        e.printStackTrace();
        System.out.println("Terjadi kesalahan saat mengembalikan barang.");
    } finally {
        refreshComboBox(); // Refresh ComboBox untuk menampilkan data terbaru
    }
    }//GEN-LAST:event_kembaliBarangActionPerformed

    private void onComboBarangSelection(java.awt.event.ItemEvent evt) {
    String selectedItem = (String) ComboBarang.getSelectedItem();

    if (selectedItem == null || selectedItem.isEmpty()) {
        return; // Abaikan jika tidak ada item yang dipilih
    }

    // Data yang ditampilkan sudah ada di ComboBox, jadi tidak perlu TextField tambahan.
    System.out.println("Selected: " + selectedItem);
}
    private void KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasActionPerformed
        // TODO add your handling code here:
        new DaftarKelas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KelasActionPerformed

    private void ComboBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBarangActionPerformed

    private void ComboBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBarangItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBarangItemStateChanged

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengembalianBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengembalianBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengembalianBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengembalianBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengembalianBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBarang;
    private javax.swing.JButton Kelas;
    private javax.swing.JButton barang;
    private javax.swing.JButton beranda;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton kembaliBarang;
    // End of variables declaration//GEN-END:variables
}
